# Generated by Django 3.1.6 on 2021-02-01 20:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=300)),
                ('ingredients', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('steps', models.TextField(max_length=1000)),
                ('time', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=32)),
                ('isFavorite', models.BooleanField()),
            ],
        ),
    ]
