# Generated by Django 3.1.6 on 2021-02-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterchef_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
